### PR TITLE
changed mysql image to use the 'per-architecture' repository for the …

### PR DESCRIPTION
**Pull request by wrigleyDan**
…amd64 builds

See https://github.com/querqy/chorus/issues/86#issuecomment-1007550553 for additional details.

### CODE REVIEW

**Comment by epugh** [comment]
Worked great

**Comment by epugh** [comment]
Would you be interested in opening a similar PR and testing the build in github.com/o19s/quepid ?

**Comment by epugh** [comment]
(I think there might have been another odd issue in Quepid and Apple Silicon.)

**Comment by wrigleyDan** [comment]
> Would you be interested in opening a similar PR and testing the build in github.com/o19s/quepid ?

Absolutely! Should I open a separate issue for that or is there already an issue that I can reference?

**Comment by epugh** [comment]
I was positive there was an issue, but I never found it.  If you are just opening a PR to fix something, and you don't need discussion about the issue, feel free to skip creating the issue.

**Pull request merged**
