### PR TITLE
Introduce Observability, and Harden quickstart.sh

### PR DESCRIPTION
**Pull request by epugh**
first cut, we have solr exporter, prometheus wired together.  Grafana… requires manual steps to connect to prometheus, will do that next.

I'm curious if, while this is oriented at more Devops (SearchOps!) level issues, could it be used to flagged other types of more ecommerce issues?  under preforming searches?    Volume of searches with no checkouts...?

Not sure if we actually want to merge this in, however, observability is critical to any search platform.

### CODE REVIEW

**Comment by epugh** [comment]
I have Solr -->  Solr Exporter --> Prometheus working.   I have tested the Prometheus --> Grafana steps by manually clicking aorund.   I have not wired in the steps to create a proper Grafana user (same account as for quepid maybe??) or the install of the Solr Dashboard via grafana.com.

I would love to come up with some rules to drive alerts as well ;-)

**Comment by epugh** [comment]
Screenshot at Oct 25 12-16-29
Screenshot at Oct 25 12-17-21

**Comment by epugh** [comment]
Should we add Zookeeper as well?  https://zookeeper.apache.org/doc/r3.6.1/zookeeperMonitor.html#Prometheus

**Comment by epugh** [comment]
zksummary
zk2

I am testing out Solr 8.7, which gives us a cleaner way to deploy rules.txt, and having some ZK issues...

**Comment by renekrie** [comment]
Great! - We haven't officially tested Querqy with Solr 8.7. yet so you're testing this as well ;-) I wish we could have a test suit in querqy-solr: Docker configs with all the combinations of JDK, Solr, Querqy versions so that this type of test could be automated easily (somehow related to https://github.com/querqy/querqy/issues/107#issuecomment-719476165)

**Comment by epugh** [comment]
Screenshot at Nov 10 12-53-26

**Comment by epugh** [comment]
I am getting closer.  Going to test out SMUI and Querqy on the boosting of "laptop" and "notebook" queries and see hhow that goes.

**Comment by epugh** [comment]
We definitly need some CI testing here...

**Comment by epugh** [comment]
See #12

**Comment by epugh** [comment]
So….  I’m afraid my branch introduce_logging has grown a bit out of control.   :disappointed:.   First off, it doesn’t have anything to do with logging at all, it’s all about observability.  I didn’t realize that at first!   So it introduces grafana and prometheus.   That led to an upgrade of Zookeeper and Solr to 8.7 to support the latest prometheus <--> zookeeper support.   The addition of these new services uncovered some races conditions in how we start things up, so quickstart.sh commands would run before services were ready.   Which led to me adding some state polling in quickstart.sh.   I then, seperately started a add_ci branch to add some smoketests, however it definitly needed all the state polling stuff, so I merged add_ci into introduce_logging…..    sigh.

the good news however is that at this point, I believe the quickstart script is MUCH more reliable.  Plus we have Github actions running the basic smoke test: https://github.com/querqy/chorus/runs/1435593290


it’s super super slow to run the actions because we don’t cache any of the docker layers…. i can’t quite figure out how to do that.   So we run the blacklight build over and over…. along with all the others…

Oh, and I rolled in some better messaging in quickstart.sh to colour code messages in blue and gray and red dependending on what is being ocmmunicated…

oh, and lastly part deux, I added an optional parameter to quickstart.sh which is -o | --with-observability so that you have to opt into the grafana/prometheus stuff, since many folks won’t care about that….

And we have our first “green” CI: https://github.com/querqy/chorus/pull/23/checks?check_run_id=1435696542

**Comment by renekrie** [comment]
@epugh I'm always getting the below warning on startup - should I be worried? Should we mention this in the docs?


```
[QUICKSTART] Create ecommerce collection.
The currently defined JAVA_HOME (/usr/local/openjdk-11) refers to a location
where java was found but jstack was not found. Continuing.
Re-using existing configuration directory ecommerce
Created collection 'ecommerce' with 2 shard(s), 1 replica(s) with config-set 'ecommerce'
WARN  - 2020-11-25 16:00:31.226; org.apache.zookeeper.ClientCnxn; An exception was thrown while closing send thread for session 0x10015a3631a0004. => EndOfStreamException: Unable to read additional data from server sessionid 0x10015a3631a0004, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x10015a3631a0004, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77) ~[zookeeper-3.6.2.jar:3.6.2]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.6.2.jar:3.6.2]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275) ~[zookeeper-3.6.2.jar:3.6.2]
[QUICKSTART]    sleep 5
[QUICKSTART] Populating products, please give it a few minutes!
```

**Review by renekrie — APPROVED** [review]
We should deal with the ZK warning in the comments but that's not a blocker.

**Comment by epugh** [comment]
There are actually two separate and ignorable warnings!!!   The first one I opened a Solr Kira to relive, the second zk one is something I don’t yet have a solve for, but appears ignorable

**Pull request merged**
