### PR TITLE
We should use API's with Solr whenever possible, and NOT the solr CLI.

### PR DESCRIPTION
**Pull request by epugh**
This first commit demonstrates using the create collection command via the API.   

Should we move to the V2 api's?  Probably, that is the future!

### CODE REVIEW

**Comment by epugh** [comment]
Okay, just discovered the Collections API v2 isn't documented in the Solr Ref Guide ;-(

**Comment by vincetrumental** [comment]
Hi Eric, 
I assume that you are (as I am) not totally convinced by the "self documenting" v2 API. I don't know if it's the future since I hardly saw it evolve since it's introduction, and i must admit I prefer the sometimes baroque v1 API. Especially in scripts, where I find it more convenient to have a single-line URL with parameters, rather than posting a piece of json.

**Comment by epugh** [comment]
Thanks for the feedback @vincetrumental ...    I think, and we can blame Elasticsearch, that world has moved on to using JSON in more and more places to write out queries ;-)    As a crusty old Solr guy, I struggle to adopt the new thing too!   

V2 api's have a bit of chicken and egg...  until people use them, they don't get documented.  if they aren't documented, they won't get used and improved.   It's somethign I'm interested in...

**Comment by epugh** [comment]
and I'm now working on SOLR-11646 to add docs to the ref guide.   Sigh.

**Pull request merged**
