### PR TITLE
Step one of global user management

### PR DESCRIPTION
**Pull request by epugh**
Step one of making Chorus more enterprise friendly is to make SSO easier.  We're doing this in Chorus by supporting oAuth, with  Keycloak as the "demo" system.   This PR integrates Quepid with Keycloak, so you don't need to create an account in Quepid, instead you register with Keycloak.

We'll expand this in the future to SMUI and Solr.   See the related PR #47 for some earlier work that didn't quite mature!

### CODE REVIEW

**Comment by renekrie** [comment]
I guess this should be marked as WIP instead of PR so that it doesn't get merged ;-)

**Comment by epugh** [comment]
I flipped on the Draft tag, thanks @renekrie ....     This is is ready to go as soon as Solr 8.11 gets released...   Or, if Querqy worked with Lucene 9....   hint hint ;-)    I am pretty stoked to have the user authentication story being simplified...

**Comment by epugh** [comment]
Oh, and i have no idea why the smoke test won't run...    something pending on something...   May need to rethink how we do smoketesting...

**Comment by epugh** [comment]
lots of progress, down to I can't get JSONP with Basic Auth to work...    I think we need to make it publice (and or swap to cors in Solr!!)

**Comment by epugh** [comment]
Okay, now with the latest Solr, keycloak, and Quepid, this all seems to be working!!!!

**Pull request merged**
