### PR TITLE
bump keycloak to work on arm chips

### PR DESCRIPTION
**Pull request by epugh**

### CODE REVIEW

**Comment by epugh** [comment]
@david-fisher @atarora   @wrigleyDan could one of you with the new M1 chips give this a try?   I *think* I've got us on the latest Keycloak with the M1 friendly build.  If this works, we might want to do this for the ES ediiton.

**Comment by epugh** [comment]
This needs to be completed before this is merged: https://github.com/o19s/quepid/issues/528

**Comment by wrigleyDan** [comment]
I'll take a look and give it a try!

**Comment by wrigleyDan** [comment]
Checked out the PR and ran it with `./quickstart.sh --with-offline-lab`

All components were successfully built and are up and running. 

Authenticating with Keycloak to access Solr works, but when trying that for Quepid it redirected me to a page that does not exist:

image

Were you able to access Quepid by using Keycloak for authentication?

**Comment by epugh** [comment]
Not until https://github.com/o19s/quepid/issues/528 is completed!!!

**Comment by wrigleyDan** [comment]
Got it, thanks for clarifying. I first read the comment the other way round 👀 

So my work here is done ✔️ 

Let me know if I can help otherwise.

**Pull request merged**
