### PR TITLE
Upgrade to Querqy5 

### PR DESCRIPTION
**Pull request by epugh**
Upgrading to the latest Querqy, and the latest SMUI!

### CODE REVIEW

**Review by renekrie — CHANGES_REQUESTED** [review]
I think we are using the word break and the replace rewriters -> they should not be removed.

Looks good apart from this.

**Comment by renekrie** [comment]
Also, the Querqy Request Handler needs a property `inMemory=true`, which I had forgotten in the migration guide. I'm going to amend this PR.

**Comment by epugh** [comment]
Thanks, I didn't know about this!

**Comment by epugh** [comment]
LGTM

**Pull request merged**
